<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span><ul class="toc-item"><li><span><a href="#Общая-информация-о-данных." data-toc-modified-id="Общая-информация-о-данных.-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Общая информация о данных.</a></span></li><li><span><a href="#Удаление-дубликатов." data-toc-modified-id="Удаление-дубликатов.-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Удаление дубликатов.</a></span></li><li><span><a href="#Изменение-типа-данных" data-toc-modified-id="Изменение-типа-данных-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Изменение типа данных</a></span></li><li><span><a href="#Переименование-столбцов-датафрейма" data-toc-modified-id="Переименование-столбцов-датафрейма-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Переименование столбцов датафрейма</a></span></li></ul></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span><ul class="toc-item"><li><span><a href="#Создадим-свой-собственный-класс-линейной-регрессии" data-toc-modified-id="Создадим-свой-собственный-класс-линейной-регрессии-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Создадим свой собственный класс линейной регрессии</a></span></li><li><span><a href="#Выделение-целевого-признака" data-toc-modified-id="Выделение-целевого-признака-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Выделение целевого признака</a></span></li><li><span><a href="#Создание-обратимой-матрицы" data-toc-modified-id="Создание-обратимой-матрицы-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Создание обратимой матрицы</a></span></li><li><span><a href="#Создадим-модели." data-toc-modified-id="Создадим-модели.-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Создадим модели.</a></span></li></ul></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span><ul class="toc-item"><li><span><a href="#Запрограммируем-алгоритм" data-toc-modified-id="Запрограммируем-алгоритм-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Запрограммируем алгоритм</a></span></li><li><span><a href="#Общий-вывод" data-toc-modified-id="Общий-вывод-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Общий вывод</a></span></li></ul></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span></a></span></li></ul></div>

**Инструкция по выполнению проекта**

1)Загрузите и изучите данные.

2)Ответьте на вопрос и обоснуйте решение.
Признаки умножают на обратимую матрицу. Изменится ли качество линейной регрессии? (Её можно обучить заново.)

a. Изменится. Приведите примеры матриц.

b. Не изменится. Укажите, как связаны параметры линейной регрессии в исходной задаче и в преобразованной.

3)Предложите алгоритм преобразования данных для решения задачи. Обоснуйте, почему качество линейной регрессии не поменяется.

4)Запрограммируйте этот алгоритм, применив матричные операции. Проверьте, что качество линейной регрессии из sklearn не отличается до и после преобразования. Примените метрику R2.

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

Подгружаем необходимые для работы библиотеки.

In [1]:
import os

import numpy as np
import pandas as pd

from sklearn.metrics import r2_score

Загружаем данные для проекта.

In [2]:
pth_1 = 'insurance.csv'
pth_2 = '/datasets/insurance.csv'

if os.path.exists(pth_1):
    something_private = pd.read_csv(pth_1)   
elif os.path.exists(pth_2):
    something_private = pd.read_csv(pth_2)
else:
    print('No data - no fun!')

### Общая информация о данных.

In [3]:
#посмотрим что там внутри
something_private.head()

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

Выведем размеры датасета.

In [4]:
print("Размерность исходных данных:", something_private.shape)

Размерность исходных данных: (5000, 5)


In [5]:
# посмотрим структуру датасета

something_private.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


In [6]:
# проверим, есть ли пропуски

something_private.isnull().sum()

Пол                  0
Возраст              0
Зарплата             0
Члены семьи          0
Страховые выплаты    0
dtype: int64

In [7]:
print('Явных дубликатов:', something_private.duplicated().sum())

Явных дубликатов: 153


Проопусков нет, полет нормальный! Я бы изменила тип данных с плавающей точкой, на целочисленные, так как в данных нет десятых частей и я посчитала нужным изменить тип. Также  имеются дубликаты, от которых хочу избавиться (хоть есть большой соблазн не трогать, потому что размер датафрейма идеально пропорционален.

Еще я заметила, что столбцы в датафрейме нарушают описанные раннне в практикуме требования, и не смотря на то, что в заднии нет пункта об обработке данных, я решила, что их лучше изменить.

### Удаление дубликатов.

#Удалим явные дубликаты из данных.
something_private = something_private.drop_duplicates(keep='first')

### Изменение типа данных

In [8]:
#изменим тип данных с плавающей точкой на целочисленные

something_private['Возраст'] = something_private['Возраст'].astype('int') 

In [9]:
#изменим тип данных с плавающей точкой на целочисленные

something_private['Зарплата'] = something_private['Зарплата'].astype('int') 

### Переименование столбцов датафрейма

In [10]:
something_private= something_private.rename(
    columns={
        'Пол': 'gender',
        'Возраст': 'age',
        'Зарплата': 'salary',
        'Члены семьи': 'family_member',  
        'Страховые выплаты': 'insurance_payments',
    }
)

In [11]:
something_private.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender              5000 non-null   int64
 1   age                 5000 non-null   int64
 2   salary              5000 non-null   int64
 3   family_member       5000 non-null   int64
 4   insurance_payments  5000 non-null   int64
dtypes: int64(5)
memory usage: 195.4 KB


В ходе первого этапа была получена информация о данных, удалены дубликаты, изменены типы данных двух столбцов (Зарплата и возраст). Таже были переименованы столбцы датафрема (для обучения они не важны, но решила все же их подправить под требования).

## Умножение матриц

### Создадим свой собственный класс линейной регрессии

In [12]:
class CustomLinReg:
    """Собственный класс линейной регрессии, для наглядности происходящего."""
    def fit(self, train_features, train_target):
        """Метод обучения модели."""
        X = np.concatenate((np.ones((train_features.shape[0], 1)), train_features), axis=1)
        y = train_target
        w = (np.linalg.inv(X.T.dot(X)).dot(X.T)).dot(y)
        self.w = w[1:]
        self.w0 = w[0]

    def predict(self, test_features):
        """Метод предсказания целевого признака."""
        return test_features.dot(self.w) + self.w0

### Выделение целевого признака

In [13]:
features = something_private.drop('insurance_payments', axis=1)
target = something_private['insurance_payments']

### Создание обратимой матрицы

Для ответа на вопрос, который указан во втором пункте 

**Признаки умножают на обратимую матрицу. Изменится ли качество линейной регрессии? (Её можно обучить заново.)**

Создадим две случайных обратимых матрицы.

In [14]:
#np.random.seed(12345)
random_matrix_1 = np.random.normal(size=(4,4))
random_matrix_2 = np.random.normal(size=(4,4))

Проверим, обратимы ли случайные матрицы.

Критерий обратимости: матрица обратима тогда и только тогда, 
когда она невырождена, то есть её определитель не равен нулю.

In [15]:
print('Определитель случайной матрицы 1:', np.linalg.det(random_matrix_1))
print('Определитель случайной матрицы 2:', np.linalg.det(random_matrix_2))

Определитель случайной матрицы 1: -1.3023485381549165
Определитель случайной матрицы 2: -0.17799919353374055


Определители не нулевые - матрицы обратимы.
Попробуем вывести обратные матрицы:

In [16]:
print(np.linalg.inv(random_matrix_1))
print(np.linalg.inv(random_matrix_2))

[[ 0.3480236   0.11956266  0.56633558  0.12612545]
 [ 0.4001255  -0.36594895  0.34626445 -0.28268795]
 [-2.26145686 -0.47250144 -0.59701058  0.64669794]
 [ 0.55623888 -0.62006161 -0.56020362  0.61854656]]
[[ 2.85560482  0.35050834  1.09442456  1.14268744]
 [-2.23220342  0.56112308 -0.86112402 -2.23933441]
 [-8.76471515 -2.10001742 -2.95609962 -4.40551388]
 [15.15989545  2.99887203  4.43373498  7.09268338]]


Зашифруем исходные признаки умножением на наши случайные матрицы:

In [17]:
multiplied_matrix_1 = features.values@random_matrix_1
multiplied_matrix_2 = features.values@random_matrix_2

print(multiplied_matrix_1.shape)
print(multiplied_matrix_2.shape)

(5000, 4)
(5000, 4)


### Создадим модели.

In [18]:
model_1 = CustomLinReg()
model_1.fit(features, target)
predictions_1 = model_1.predict(features)
model_1_r2 = r2_score(target, predictions_1)

In [19]:
print('R2 для модели 1 обученной на исходных данных:', model_1_r2.round(5))

R2 для модели 1 обученной на исходных данных: 0.42495


In [20]:
model_2 = CustomLinReg()
model_2.fit(multiplied_matrix_1, target)
predictions_2 = model_2.predict(multiplied_matrix_1)
model_2_r2 = r2_score(target, predictions_2)

In [21]:
print('R2 для модели 2 обученной на преобразованных данных:', model_2_r2.round(5))

R2 для модели 2 обученной на преобразованных данных: 0.42495


In [22]:
model_3 = CustomLinReg()
model_3.fit(multiplied_matrix_2,target)
predictions_3 = model_3.predict(multiplied_matrix_2)
model_3_r2 = r2_score(target, predictions_3)

In [23]:
print('R2 для модели 3 обученной на преобразованных данных:', model_3_r2.round(5))

R2 для модели 3 обученной на преобразованных данных: 0.42495


Преобразование данных практически никак не влияет на качество обучения модели, зато позволяет применить алгоритмы преобразования данных с целью их обезличивания.

## Алгоритм преобразования

- Создадим случайную матрицу P
- Проверяем, обратима ли матрица P
- Умножим матрицу признаков на матрицу P 
- Сравниваем метрику R2 на исходных и на преобразованных признаках
- Проанализируем результат

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

**Обоснование**

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

При умножении мтрицы на обратную ей матрицу получается единичная матрица $E$:

$$
AA^{-1} = A^{-1}A = E
$$


Умножим $X$ на обратимую случайную матрицу $P$, получим измененную матрицу признаков $X_p$:

$$
X_p = XP
$$

Запишем формулу обучения для измененной матрицы $X_p$:

$$
w_p = (X_p^T X_p)^{-1} X_p^T y = ((XP)^T XP)^{-1} (XP)^T y
$$

Учтём, что транспонированное произведение матриц равно произведению транспонированных матриц, взятых в обратном порядке:

$$
(A B)^T = B^T A^T
$$

Тогда можем преобразовать $w_p$:

$$
w_p = (P^T (X^T X) P)^{-1} (XP)^T y = (P^T (X^T X) P)^{-1} P^T X^T y = (X^TX)^{-1}(P^TP)^{-1}P^T X^T y = (X^TX)^{-1}P^{-1} (P^T)^{-1}P^T X^T y =(X^TX)^{-1}P^{-1} X^T y
$$
$$
w_p = P^{-1} w
$$

Следовательно, предсказания для измененной матрицы:

$$
a_p = (XP)w_p = (XP)P^{-1}w
$$
$$
a = Xw = XEw = XPP^{-1}w = (XP)P^{-1}w
$$

$$
a_p = a
$$

Предсказания не изменятся, если домножить матрицу обучающих признаков на случайную обратимую матрицу. Алгоритм обоснован.


**Обоснование, попытка ~вторая~ третья**

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$


Докажем, что предсказания $a$ на исходной матрице равны предсказаниям $a_p$
на исходной матрице, умноженной на случайную обратимую матрицу $P$.

В процессе доказательства воспользуемся свойствами:

$$
(AB)^T=B^T A^T
$$
$$
(AB)^{-1} = B^{-1} A^{-1}
$$
$$
A A^{-1} = A^{-1} A = E
$$
$$
AE = EA = A
$$

**1** Умножим $X$ на обратимую случайную матрицу $P$, получим измененную матрицу признаков $X_p$:

$$
X_p = XP
$$

**2** Запишем формулу обучения для измененной матрицы $X_p$:

$$
w_p = (X_p^T X_p)^{-1} X_p^T y = ((XP)^T XP)^{-1} (XP)^T y
$$

**3** Преобразуем $w_p$:

$$
w_p = (P^T (X^T X P))^{-1} P^T X^T y
$$ 

$$
 = (X^T X P)^{-1} (P^T)^{-1} P^T X^T y
$$

$$
 = ((X^T X) P)^{-1} E X^T y
$$

$$
 = P^{-1} (X^T X)^{-1} X^T y
$$


Следовательно, получаем:

$$
w_p = P^{-1} w
$$

**4** Сравним редсказания $a$ и редсказания для 
измененной матрицы $a_p$:

$$
a = Xw
$$

$$
a_p = X P w_p = X P P^{-1} w
$$

$$
= X E w = X w
$$

Следовательно 

$$
a_p = a
$$

ПОЛУЧИЛОСЬ!)))
Предсказания не изменятся, если домножить матрицу обучающих признаков на случайную обратимую матрицу. Алгоритм обоснован.


## Проверка алгоритма

### Запрограммируем алгоритм

In [24]:
class SecureLinReg:
    """Улучшенная пользовательская модель линейной регрессии.
    В методах fit и predict признаки теперь
    по умолчанию умножаются на случайную матрицу P.
    """
    
    def proper_random_matrix(self, matrix):
        """Метод принимает в качестве аргумента случайную матрицу,
        проверяет ее на обратимость, в случае успеха возвращает матрицу
        без изменений. В случае неудачи генерирует новую случайную матрицу
        и рекурсивно вызывает сам себя с этой новой матрицей на входе.
        """
        determinant = np.linalg.det(matrix)
        if determinant == 0:
            another_matrix = np.random.normal(size=(4,4))
            P = proper_random_matrix(another_matrix)
            return P
        return matrix
    
    def fit(self, train_features, train_target):
        """Метод обучения модели."""
        P = np.random.normal(size=(4,4))
        P = self.proper_random_matrix(P)
                  
        cyphered_features = train_features.values@P
        
        X = np.concatenate((np.ones((cyphered_features.shape[0], 1)), cyphered_features), axis=1)
        y = train_target
        w = (np.linalg.inv(X.T.dot(X)).dot(X.T)).dot(y)
        self.w = w[1:]
        self.w0 = w[0]
        self.P  = P
        
    def predict(self, test_features):
        """Метод предсказания целевого признака."""
        cyphered_features = test_features.values@self.P
        
        return cyphered_features.dot(self.w) + self.w0

Создадим и обучим обновленную модель линейной регрессии

In [25]:
# создаем модель...

secure_model = SecureLinReg()

In [26]:
# обучаем на исходных данных

secure_model.fit(features, target)

In [27]:
# трясём с нее предсказания...

predictions = secure_model.predict(features)

In [28]:
# ...и выводим метрику R2

secure_model_r2 = r2_score(target, predictions)

print('R2 для безопасной модели, обученной на исходных данных:', secure_model_r2.round(5))

R2 для безопасной модели, обученной на исходных данных: 0.42495


### Общий вывод

В ходе данной работы было практически (сравнение показателей метрики R2) и математически доказано, что умножение исходной матрицы признаков на любую случайную матрицу(при условии, что она обратима) никак не влияет на способность модели предсказывать целевой признак. Составленный на основе этого наблюдения алгоритм целесообразно использовать для обезличивания исходых данных. Спасибо за внимание!